"Changes: Audio":
  - changed-files:
      - any-glob-to-any-file: '**/*.ogg'

"Changes: C#":
  - changed-files:
      - all-globs-to-all-files: '**/*.cs'

"Changes: ftl":
  - changed-files:
      - any-glob-to-any-file: '**/*.ftl'

"Changes: Sprites":
  - changed-files:
      - any-glob-to-any-file: '**/*.rsi/*.png'

"Changes: Map":
  - changed-files:
      - any-glob-to-any-file:
          - 'Resources/Maps/**/*.yml'
          - 'Resources/Prototypes/Maps/**/*.yml'

"Changes: UI":
  - changed-files:
      - any-glob-to-any-file: '**/*.xaml*'

"Changes: yml":
  - changed-files:
      - any-glob-to-any-file: '**/*.yml'
